version: '3'

services:
  jupyter:
    container_name: interpreter
    build: .
    ports:
      - "8888:8888"
      - "8000:8000"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - PYTHONPATH=/home/jovyan
    entrypoint: ["sh", "-c", "start-notebook.sh --NotebookApp.token='' & uvicorn api:app --host 0.0.0.0 --port 8000"]
    volumes:
      - ./uploads:/tmp
